### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zularizal** [CapPow/collBook#2]
Hi @CapPow , I'm a graphic designer. I am interested and like your project. I want to contribute by designing a logo for your project.
Can I contribute?

**Comment by CapPow** [comment]
@zularizal, We'd love it! If I can also point you to [the companion repo for collNotes](https://github.com/j-h-m/collNotes). Since the mobile app is designed to work in tandem with the desktop, We'd love to use the same logo for both. Thanks for reaching out!

**Comment by zularizal** [comment]
![bitmap](https://user-images.githubusercontent.com/38547278/55207951-e49c9e80-520e-11e9-98a3-6ed3d409495e.png)
Hi @CapPow , sorry it's too late. I have designed several logos for your project. The logo of the logo is inspired by a letter C, books, notes, cells and molecules.
And also I have made it in several colours.
What do you think? Which one is good for you? left, centre or right

If there is something you want to change, let me know.

**Comment by CapPow** [comment]
@zularizal,
This is fantastic work! After speaking with @j-h-m I think we both agree the upper right logo is most fitting, although they're all impressive. I'd love for your name to appear as a contributor for both projects, would you be willing to make a pull request adding the logo to into these folders:
- https://github.com/j-h-m/collNotes/tree/master/data/assets
- https://github.com/CapPow/collBook/tree/master/ui/resources

Thanks for your time!

**Comment by zularizal** [comment]
Hi @CapPow , I have made a pull request on both projects. #3 

And also I have uploaded the master logos to the drive. Check this link.
https://drive.google.com/open?id=1pjuyUMxOoF4k31NSXEwRZHXhW7hGvyDN

**Comment by j-h-m** [comment]
@zularizal Thanks for the logos! 👍

**Comment by zularizal** [comment]
You are welcome. If you need a logo for your open source project. Don't hesitate to contact me. Because it's free.

**Comment by CapPow** [comment]
@zularizal ,

Thanks so much for the collaboration! I'd love to thank you in the credits section of our readme. Let me know if you have a website you'd like me to direct people to.
